In [37]:
import pandas as pd
import numpy as np

df = pd.read_excel('electronika_clean.xlsx')
df

,Unnamed: 0,Order_ID,Email_new,Phone_new,Source,OrderDate,время,месяц,ChangeDate,DeliveryDate,...,Quant,RowPrice,RowDiscount,RowSum,Brand,TN,TK,NomFullPath,Week,Nom_ID
0,10,1303000511_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:46:45.000,201603,2016-03-05 09:16:49.000,2016-03-01 00:00:00.000,...,1,2970,0,2970,Ника,Товары для дома,Хозтовары,Техника для дома/Техника для ухода за одеждой/...,9,90364
1,12,1303000512_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:47:19.000,201603,2016-03-01 10:59:43.000,2016-03-01 00:00:00.000,...,1,19490,0,19490,DeLonghi,Мелкая бытовая техника,Приготовление пищи,Техника для кухни/Приготовление пищи/Мультиварки/,9,45673
2,14,1303000513_TT,666668112117_pu19@ya.ru,55575655-50555350534877,Онлайн-Резерв.,2016-03-11,16:06:56.000,201603,2016-03-11 20:11:18.000,2016-03-12 00:00:00.000,...,1,19990,0,19990,Samsung,ТВ-Аудио,Телевизоры LCD,"Телевизоры, аудио, видео/Телевизоры/LED телеви...",10,120757
3,16,1303000514_TT,666668112117_pu19@ya.ru,55575653-57485657505272,Онлайн-Резерв.,2016-03-15,18:13:33.000,201603,2016-03-15 18:17:35.000,2016-03-22 00:00:00.000,...,1,23680,0,23680,СМК,Мебель,Мягкая мебель,Мебель/Мягкая мебель/Диваны/Трехместные диваны/,11,264580
4,28,1303000520_TT,56666668112117_pu26@yanded.ru,55575449-54535553535073,Онлайн-Резерв.,2016-03-01,00:01:46.000,201603,2016-03-04 15:09:38.000,2016-03-02 00:00:00.000,...,1,2420,0,2420,HP,Аксессуары,Картриджи и бумага,"Компьютеры, ноутбуки, планшеты/Оргтехника/Расх...",9,76102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183067,357019,5898089_BX,6666449117_1u9@bk.ru,55574957-51495048515075,Онлайн-Резерв.,2016-04-30,23:51:37.000,201604,2016-05-03 12:55:07.000,2016-05-02 00:00:00.000,...,1,899,0,899,Saturn,Климат,Вентиляторы бытовые,Техника для дома/Климатическая техника/Кондици...,17,38755
183068,357021,5898095_BX,666661118109_vm27@yahoo.com,55575452-55554849505278,Онлайн-Резерв.,2016-04-30,23:54:03.000,201604,2016-05-04 19:43:40.000,2016-05-07 00:00:00.000,...,1,1090,0,1090,Case Logic,Аксессуары,Аксессуары для фото/видео,Фото- и видеотехника/Аксессуары для фото и вид...,17,31908
183069,357023,5898099_BX,3110116_nt16@pisem.net,55574948-50554849554878,Онлайн-Резерв.,2016-04-30,23:56:02.000,201604,2016-05-01 11:57:42.000,2016-05-08 00:00:00.000,...,1,6859,0,6859,ELIKOR,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Вытяжки/,17,140459
183070,357024,5898102_BX,55666665102117_fu13@list.ru,55575648-51484956545071,Онлайн-Резерв.,2016-04-30,23:56:38.000,201604,2016-05-06 20:18:49.000,2016-05-05 00:00:00.000,...,1,9120,0,9120,FORWARD,Спорт и активный отдых,Велосипеды и аксессуары,Товары для спорта и отдыха/Велосипеды и аксесс...,17,295956
183071,357027,5898108_BX,566102117_fu20@rambler.ru,55574851-54534948525271,Онлайн-Резерв.,2016-04-30,23:57:42.000,201604,2016-05-09 09:10:30.000,2016-05-04 00:00:00.000,...,1,900,0,900,Hasbro,Детские товары,Игрушки,Детские товары/Игрушки/Творчество и развитие р...,17,123514

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183072 entries, 0 to 183071
Data columns (total 38 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    183072 non-null  int64
 1   Order_ID      183072 non-null  object
 2   Email_new     183072 non-null  object
 3   Phone_new     183072 non-null  object
 4   Source        183072 non-null  object
 5   OrderDate     183072 non-null  datetime64[ns]
 6   время         183072 non-null  object
 7   месяц         183072 non-null  int64
 8   ChangeDate    183072 non-null  object
 9   DeliveryDate  183072 non-null  object
 10  PaymentDate   183072 non-null  object
 11  Status        183072 non-null  object
 12  Status_ID     183072 non-null  int64
 13  OneClick      183072 non-null  int64
 14  CancelReason  64955 non-null   object
 15  Actions       51686 non-null   object
 16  DeliveryType  179098 non-null  object
 17  PaymentType   183072 non-null  object
 18  Region        183071 non-null  object
 19  Area          182244 non-null  object
 20  Store_ID      183072 non-null  int64
 21  FullSum       183072 non-null  float64
 22  Discount      183072 non-null  int64
 23  IM_Rozn_Sum   183072 non-null  float64
 24  Row_ID        183072 non-null  int64
 25  Articul       183072 non-null  int64
 26  Nom_Name      183062 non-null  object
 27  NomGroup      183072 non-null  object
 28  Quant         183072 non-null  int64
 29  RowPrice      183072 non-null  int64
 30  RowDiscount   183072 non-null  int64
 31  RowSum        183072 non-null  int64
 32  Brand         182343 non-null  object
 33  TN            182387 non-null  object
 34  TK            182387 non-null  object
 35  NomFullPath   183072 non-null  object
 36  Week          183072 non-null  int64
 37  Nom_ID        183072 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(14), object(21)
memory usage: 53.1+ MB

In [41]:
all = df[['месяц', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['месяц']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all['Avg goods'] = (all['Quant'] / all['Order_ID']).apply(lambda x: round(x, 2))
all['Avg order'] = (all['RowSum'] / all['Order_ID']).apply(lambda x: round(x, 2))
all['Avg client'] = (all['RowSum'] / all['Phone_new']).apply(lambda x: round(x, 2))
all.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

total = df[['RowSum', 'Order_ID', 'Phone_new', 'Quant']] \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
total_dict = {
    'RowSum': [total.iloc[0]],
    'Order_ID': [total.iloc[1]],
    'Phone_new': [total.iloc[2]],
    'Quant': [total.iloc[3]]
}
total_df = pd.DataFrame().from_dict(total_dict)
total_df
total_df['Avg goods'] = (total_df['Quant'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg order'] = (total_df['RowSum'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg client'] = (total_df['RowSum'] / total_df['Phone_new']).apply(lambda x: round(x, 2))
total_df.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)
all = pd.concat([all, total_df], axis=0)


sold = df[df['Status_ID'] == 14][['месяц', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['месяц']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold['Avg goods'] = (sold['Quant'] / sold['Order_ID']).apply(lambda x: round(x, 2))
sold['Avg order'] = (sold['RowSum'] / sold['Order_ID']).apply(lambda x: round(x, 2))
sold['Avg client'] = (sold['RowSum'] / sold['Phone_new']).apply(lambda x: round(x, 2))
sold.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

total = df[df['Status_ID'] == 14][['RowSum', 'Order_ID', 'Phone_new', 'Quant']] \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
total_dict = {
    'RowSum': [total.iloc[0]],
    'Order_ID': [total.iloc[1]],
    'Phone_new': [total.iloc[2]],
    'Quant': [total.iloc[3]]
}
total_df = pd.DataFrame().from_dict(total_dict)
total_df
total_df['Avg goods'] = (total_df['Quant'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg order'] = (total_df['RowSum'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg client'] = (total_df['RowSum'] / total_df['Phone_new']).apply(lambda x: round(x, 2))
total_df.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)
sold = pd.concat([sold, total_df], axis=0)

In [42]:
all

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,909596099,82876,66387,101273,1.22,10975.39,13701.42
201604,838498021,76262,61036,94657,1.24,10994.97,13737.76
0,1748094120,159137,123112,195930,1.23,10984.84,14199.22

In [43]:
sold

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,506826281,53210,47796,63568,1.19,9525.02,10603.95
201604,469054488,49715,44194,60530,1.22,9434.87,10613.53
0,975880769,102925,89534,124098,1.21,9481.47,10899.56

In [44]:
(100.0 * sold / all).apply(lambda x: round(x, 2))

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,55.72,64.20,72.00,62.77,97.54,86.79,77.39
201604,55.94,65.19,72.41,63.95,98.39,85.81,77.26
0,55.83,64.68,72.73,63.34,98.37,86.31,76.76

In [47]:
all_by_category = df[['TN', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TN']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all_by_category['Avg goods'] = (all_by_category['Quant'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg order'] = (all_by_category['RowSum'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg client'] = (all_by_category['RowSum'] / all_by_category['Phone_new']).apply(lambda x: round(x, 2))
all_by_category.sort_values(by='RowSum', ascending=False, inplace=True)
all_by_category.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

sold_by_category = df[df['Status_ID'] == 14][['TN', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TN']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold_by_category['Avg goods'] = (sold_by_category['Quant'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg order'] = (sold_by_category['RowSum'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg client'] = (sold_by_category['RowSum'] / sold_by_category['Phone_new']).apply(lambda x: round(x, 2))
sold_by_category.sort_values(by='RowSum', ascending=False, inplace=True)
sold_by_category.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

In [55]:
all_by_category

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
TN,,,,,,,
Крупная бытовая техника,536245714,25656,19717,28386,1.11,20901.38,27197.13
Цифровая Техника,366442419,21344,18188,23006,1.08,17168.40,20147.48
ТВ-Аудио,240990402,10919,8698,12453,1.14,22070.74,27706.42
Мелкая бытовая техника,196911405,34446,28927,38732,1.12,5716.52,6807.18
Сделай сам,110723581,14730,12474,18708,1.27,7516.88,8876.35
Спорт и активный отдых,103966173,13996,11367,19065,1.36,7428.28,9146.32
Детские товары,78192206,12035,10086,13784,1.15,6497.07,7752.55
Мебель,35077451,7129,6073,9042,1.27,4920.39,5775.97
Климат,31237349,3288,2872,4268,1.30,9500.41,10876.51
Аксессуары,28054564,14023,12106,17362,1.24,2000.61,2317.41
Товары для дома,12508347,6291,5326,9166,1.46,1988.29,2348.54
"Игры, софт и развлечения",4539537,654,598,816,1.25,6941.19,7591.20
Услуги,371509,175,127,330,1.89,2122.91,2925.27
Элитная техника,304308,6,6,6,1.00,50718.00,50718.00
Автотовары,193460,85,74,86,1.01,2276.00,2614.32
Инсталляция,6270,1,1,30,30.00,6270.00,6270.00
"Хобби, досуг",35,1,1,1,1.00,35.00,35.00

In [49]:
sold_by_category

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
TN,,,,,,,
Крупная бытовая техника,337285730,16994,14792,18678,1.10,19847.34,22801.90
Цифровая Техника,145993355,11506,10910,12224,1.06,12688.45,13381.61
ТВ-Аудио,127306400,6575,5810,6825,1.04,19362.19,21911.60
Мелкая бытовая техника,123726232,23754,21837,25550,1.08,5208.65,5665.90
Сделай сам,66918516,9865,9170,12602,1.28,6783.43,7297.55
Спорт и активный отдых,58461240,8739,8119,11470,1.31,6689.69,7200.55
Детские товары,44690693,7457,7094,8452,1.13,5993.12,6299.79
Мебель,24655342,5270,5013,6670,1.27,4678.43,4918.28
Климат,17944052,2213,2146,2664,1.20,8108.47,8361.63
Аксессуары,17729778,9657,9002,11574,1.20,1835.95,1969.54
Товары для дома,8265472,4386,4075,6287,1.43,1884.51,2028.34
"Игры, софт и развлечения",1257575,367,350,411,1.12,3426.63,3593.07
Услуги,150433,80,64,171,2.14,1880.41,2350.52
Элитная техника,139878,3,3,3,1.00,46626.00,46626.00
Автотовары,91658,52,51,53,1.02,1762.65,1797.22
"Хобби, досуг",35,1,1,1,1.00,35.00,35.00

In [53]:
join = all_by_category.join(sold_by_category, how='left', rsuffix='_sold')
join['Доля выкупа (выручка)'] = (100.0 * join['Выручка, руб_sold'] / join['Выручка, руб']).apply(lambda x : round(x, 2))
join['Доля выкупа (количество товаров)'] = (100.0 * join['Количество товаров_sold'] / join['Количество товаров']).apply(lambda x : round(x, 2))

In [54]:
join[['Выручка, руб', 'Выручка, руб_sold', 'Доля выкупа (выручка)', 'Количество товаров', 'Количество товаров_sold', 'Доля выкупа (количество товаров)']]

,"Выручка, руб","Выручка, руб_sold",Доля выкупа (выручка),Количество товаров,Количество товаров_sold,Доля выкупа (количество товаров)
TN,,,,,,
Крупная бытовая техника,536245714,337285730.0,62.90,28386,18678.0,65.80
Цифровая Техника,366442419,145993355.0,39.84,23006,12224.0,53.13
ТВ-Аудио,240990402,127306400.0,52.83,12453,6825.0,54.81
Мелкая бытовая техника,196911405,123726232.0,62.83,38732,25550.0,65.97
Сделай сам,110723581,66918516.0,60.44,18708,12602.0,67.36
Спорт и активный отдых,103966173,58461240.0,56.23,19065,11470.0,60.16
Детские товары,78192206,44690693.0,57.15,13784,8452.0,61.32
Мебель,35077451,24655342.0,70.29,9042,6670.0,73.77
Климат,31237349,17944052.0,57.44,4268,2664.0,62.42
Аксессуары,28054564,17729778.0,63.20,17362,11574.0,66.66
Товары для дома,12508347,8265472.0,66.08,9166,6287.0,68.59
"Игры, софт и развлечения",4539537,1257575.0,27.70,816,411.0,50.37
Услуги,371509,150433.0,40.49,330,171.0,51.82
Элитная техника,304308,139878.0,45.97,6,3.0,50.00
Автотовары,193460,91658.0,47.38,86,53.0,61.63
Инсталляция,6270,NaN,NaN,30,NaN,NaN
"Хобби, досуг",35,35.0,100.00,1,1.0,100.00

In [20]:
all_by_category = df[['TK', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TK']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all_by_category['Avg goods'] = (all_by_category['Quant'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg order'] = (all_by_category['RowSum'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg client'] = (all_by_category['RowSum'] / all_by_category['Phone_new']).apply(lambda x: round(x, 2))
all_by_category.sort_values(by='RowSum', ascending=False, inplace=True)

sold_by_category = df[df['Status_ID'] == 14][['TK', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TK']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold_by_category['Avg goods'] = (sold_by_category['Quant'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg order'] = (sold_by_category['RowSum'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg client'] = (sold_by_category['RowSum'] / sold_by_category['Phone_new']).apply(lambda x: round(x, 2))
sold_by_category.sort_values(by='RowSum', ascending=False, inplace=True)

join = all_by_category.join(sold_by_category, how='left', rsuffix='_sold')
join['Доля выкупа (выручка)'] = (100.0 * join['RowSum_sold'] / join['RowSum']).apply(lambda x : round(x, 2))
join['Доля выкупа (количество товаров)'] = (100.0 * join['Quant_sold'] / join['Quant']).apply(lambda x : round(x, 2))
join.sort_values(by='RowSum', ascending=False, inplace=True)
join.rename(
    columns={
        'RowSum': 'Revenue total',
        'Order_ID': 'Orders total',
        'Phone_new': 'Clients total',
        'Quant': 'Goods total',
        'Avg order': 'Average bill total',
        'RowSum_sold': 'Revenue redeemed',
        'Доля выкупа (выручка)': 'Revenue redeemability',
        'Quant_sold': 'Goods redeemed',
        'Доля выкупа (количество товаров)': 'Goods redeemability'
    },
    inplace=True
)

join.head(20)

,Revenue total,Orders total,Clients total,Goods total,Avg goods,Average bill total,Avg client,Revenue redeemed,Order_ID_sold,Phone_new_sold,Goods redeemed,Avg goods_sold,Avg order_sold,Avg client_sold,Revenue redeemability,Goods redeemability
TK,,,,,,,,,,,,,,,,
Телевизоры LCD,226948918,7478,5382,7767,1.04,30348.88,42168.14,120590672.0,4485.0,3541.0,4595.0,1.02,26887.55,34055.54,53.14,59.16
Мобильные средства связи,202208122,10668,9093,11273,1.06,18954.64,22237.78,66398080.0,4956.0,4732.0,5217.0,1.05,13397.51,14031.72,32.84,46.28
Холодильное оборудование,191429362,7807,6152,8063,1.03,24520.22,31116.61,119899953.0,5215.0,4586.0,5337.0,1.02,22991.36,26144.78,62.63,66.19
Встраиваемая техника,183478346,9323,6855,10821,1.16,19680.18,26765.62,115362638.0,6140.0,5178.0,7099.0,1.16,18788.70,22279.38,62.88,65.60
Стиральные машины,119682526,5608,4274,5727,1.02,21341.39,28002.46,73728741.0,3601.0,3080.0,3629.0,1.01,20474.52,23937.90,61.60,63.37
Приготовление пищи,98155050,18730,15628,21173,1.13,5240.53,6280.72,59748877.0,12932.0,11814.0,13822.0,1.07,4620.23,5057.46,60.87,65.28
Компьютеры портативные,72251257,2118,1709,2214,1.05,34112.96,42276.92,30364053.0,961.0,858.0,991.0,1.03,31596.31,35389.34,42.03,44.76
Прогулки и путешествие,62409474,7091,5912,7616,1.07,8801.22,10556.41,33886944.0,4020.0,3918.0,4203.0,1.05,8429.59,8649.04,54.30,55.19
Плиты,60935209,4531,3836,4653,1.03,13448.51,15885.09,39705968.0,3128.0,2935.0,3180.0,1.02,12693.72,13528.44,65.16,68.34
Уход за домом,60059890,7063,5815,7569,1.07,8503.45,10328.44,37985089.0,4805.0,4279.0,4974.0,1.04,7905.33,8877.09,63.25,65.72
Силовая и садовая техника,54665338,5341,4650,6149,1.15,10235.04,11755.99,31464543.0,3391.0,3261.0,3844.0,1.13,9278.84,9648.74,57.56,62.51
Велосипеды и аксессуары,51469096,4293,3607,4570,1.06,11989.07,14269.23,26334670.0,2411.0,2341.0,2543.0,1.05,10922.72,11249.33,51.17,55.65
Инструменты,32286241,6059,5204,7229,1.19,5328.64,6204.12,19994966.0,4090.0,3822.0,4839.0,1.18,4888.74,5231.55,61.93,66.94
Тренажеры,31368026,2382,2128,2498,1.05,13168.78,14740.61,19576596.0,1694.0,1665.0,1738.0,1.03,11556.43,11757.72,62.41,69.58
Периферийные устройства,30766796,3423,3034,3719,1.09,8988.25,10140.67,20406951.0,2409.0,2308.0,2544.0,1.06,8471.13,8841.83,66.33,68.41
Сантехника,22623791,3661,3054,5368,1.47,6179.68,7407.92,14993215.0,2620.0,2409.0,3921.0,1.50,5722.60,6223.83,66.27,73.04
Планшеты,21191531,1773,1560,1955,1.10,11952.36,13584.31,10703948.0,1041.0,1000.0,1113.0,1.07,10282.37,10703.95,50.51,56.93
Красота и здоровье,20003641,7139,6123,7724,1.08,2802.02,3266.97,13125475.0,4957.0,4636.0,5166.0,1.04,2647.87,2831.21,65.62,66.88
Фотоаппараты,19237778,890,777,1004,1.13,21615.48,24759.05,9478070.0,515.0,494.0,570.0,1.11,18404.02,19186.38,49.27,56.77
Офис и Кабинет,15244695,2581,2268,3014,1.17,5906.51,6721.65,11000751.0,1935.0,1899.0,2205.0,1.14,5685.14,5792.92,72.16,73.16

In [21]:
join

,Revenue total,Orders total,Clients total,Goods total,Avg goods,Average bill total,Avg client,Revenue redeemed,Order_ID_sold,Phone_new_sold,Goods redeemed,Avg goods_sold,Avg order_sold,Avg client_sold,Revenue redeemability,Goods redeemability
TK,,,,,,,,,,,,,,,,
Телевизоры LCD,226948918,7478,5382,7767,1.04,30348.88,42168.14,120590672.0,4485.0,3541.0,4595.0,1.02,26887.55,34055.54,53.14,59.16
Мобильные средства связи,202208122,10668,9093,11273,1.06,18954.64,22237.78,66398080.0,4956.0,4732.0,5217.0,1.05,13397.51,14031.72,32.84,46.28
Холодильное оборудование,191429362,7807,6152,8063,1.03,24520.22,31116.61,119899953.0,5215.0,4586.0,5337.0,1.02,22991.36,26144.78,62.63,66.19
Встраиваемая техника,183478346,9323,6855,10821,1.16,19680.18,26765.62,115362638.0,6140.0,5178.0,7099.0,1.16,18788.70,22279.38,62.88,65.60
Стиральные машины,119682526,5608,4274,5727,1.02,21341.39,28002.46,73728741.0,3601.0,3080.0,3629.0,1.01,20474.52,23937.90,61.60,63.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Материалы для инсталляции,6270,1,1,30,30.00,6270.00,6270.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Ванна, баня и сауна",4218,6,6,6,1.00,703.00,703.00,4218.0,6.0,6.0,6.0,1.00,703.00,703.00,100.00,100.00
Подарки КБТ,241,12,8,20,1.67,20.08,30.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Товары для дома и офиса,35,1,1,1,1.00,35.00,35.00,35.0,1.0,1.0,1.0,1.00,35.00,35.00,100.00,100.00
Упаковка,27,3,3,3,1.00,9.00,9.00,18.0,2.0,2.0,2.0,1.00,9.00,9.00,66.67,66.67